# Generated by Django 5.1.2 on 2024-10-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='civility',
            field=models.CharField(default='Null', max_length=20),
            preserve_default=False,
        ),
    ]
